### ISSUE TITLE
address sanitizer is mad

### ISSUE THREAD

**Issue by jeffhammond** [jeffhammond/mukautuva#15]
This:
```c
    void ** pmuk_mpi_message_no_proc = MUK_DLSYM(wrap_so_handle,"IMPL_MESSAGE_NO_PROC");
    muk_mpi_message_no_proc = *pmuk_mpi_message_no_proc;
```
...triggers this error:
```
=================================================================
==489331==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7ffa935a8700 at pc 0x7ffa99acaf3d bp 0x7ffd31dd3d40 sp 0x7ffd31dd3d30
READ of size 8 at 0x7ffa935a8700 thread T0
    #0 0x7ffa99acaf3c in MUK_Alkaa /home/jhammond/mukautuva/libinit.c:507
    #1 0x7ffa99ad2384 in MPI_Init /home/jhammond/mukautuva/libinit.c:1443
    #2 0x5576e84cc61e in main /home/jhammond/mukautuva/testinit.c:29
    #3 0x7ffa98c29d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #4 0x7ffa98c29e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #5 0x5576e84cc2a4 in _start (/home/jhammond/mukautuva/testinit.x+0x12a4)

0x7ffa935a8704 is located 0 bytes to the right of global variable 'IMPL_MESSAGE_NO_PROC' defined in 'impl-predefined.c:354:13' (0x7ffa935a8700) of size 4
SUMMARY: AddressSanitizer: global-buffer-overflow /home/jhammond/mukautuva/libinit.c:507 in MUK_Alkaa
Shadow bytes around the buggy address:
  0x0fffd26ad090: 00 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad0a0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad0b0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad0c0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad0d0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
=>0x0fffd26ad0e0:[04]f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad0f0: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad100: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad110: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad120: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
  0x0fffd26ad130: 04 f9 f9 f9 f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==489331==ABORTING
```

It goes away if i meke sure that `IMPL_MESSAGE_NO_PROC` is 8 bytes, e.g. like this:
```
// No Process Message Handle
#if 0
MPI_Message IMPL_MESSAGE_NO_PROC = MPI_MESSAGE_NO_PROC;
#else
typedef union MPI_Message_union
{
    MPI_Message handle;
    void *      dummy;
} MPI_Message_union;
MPI_Message_union IMPL_MESSAGE_NO_PROC = { .handle = MPI_MESSAGE_NO_PROC };
#endif
```

I can resolve this two ways:
1. implement the `union` thing immediately above, or a more advanced version of it.
2. move completely away from using pointers to handles for the predefined stuff.

2 is preferred but requires a massive rewrite.

**Comment by jeffhammond** [comment]
check this again later.  the new design should fix it.
